/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wcs;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.math.BigInteger;
import java.net.URISyntaxException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Administration extends javax.swing.JFrame {

    /**
     * Creates new form Administration
     */
    public Administration() throws Exception {
        initComponents();
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        custom();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRATION");

        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("HOME");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(125, 48));
        jButton1.setPreferredSize(new java.awt.Dimension(125, 48));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("PAYMENTS");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(125, 48));
        jButton2.setPreferredSize(new java.awt.Dimension(125, 48));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("MESSAGES");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(125, 48));
        jButton3.setPreferredSize(new java.awt.Dimension(125, 48));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("ADMINISTRATION");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(135, 48));
        jButton4.setPreferredSize(new java.awt.Dimension(135, 48));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jLabel1.setText("AREA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUDITORIUM", "MAIN BUILDING", "MBA BUILDING", "TRAINING AND PLACEMENT", "TRAINING AND DEVELOPEMENT", "CULTURAL DEPARTMENT", "LIBRARY", "READING HALL", "WORKSHOP BUILDING", "GUEST HOUSE", "SWAMI VIVEKANAND HALL", "VIKRAM SARABHAI HALL", "RADHA KRISHNA HALL", "SHARDA HALL", "SENIOR FACULTY HALL" }));

        jLabel3.setText("ROOM_NO.");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CONTACT PERSON");

        jLabel4.setText("MOBILE NUMBER");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton5.setText("ISSUE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton6.setText("PRINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("(000 If NA)");

        jLabel6.setText("RFID ");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton7.setText("REISSUE");
        jButton7.setMaximumSize(new java.awt.Dimension(79, 27));
        jButton7.setPreferredSize(new java.awt.Dimension(79, 27));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(364, 195));
        jPanel7.setLayout(null);
        jPanel7.add(jLabel21);
        jLabel21.setBounds(10, 0, 150, 60);
        jPanel7.add(jLabel22);
        jLabel22.setBounds(358, 6, 150, 60);

        jLabel23.setBackground(new java.awt.Color(0, 255, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("WCS CARD");
        jLabel23.setOpaque(true);
        jPanel7.add(jLabel23);
        jLabel23.setBounds(378, 190, 130, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(jLabel24);
        jLabel24.setBounds(30, 66, 340, 160);

        jLabel19.setPreferredSize(new java.awt.Dimension(514, 259));
        jLabel19.setRequestFocusEnabled(false);
        jPanel7.add(jLabel19);
        jLabel19.setBounds(0, 0, 514, 259);

        jLabel26.setText("EMAIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField14))))
                .addGap(73, 73, 73)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(382, 382, 382)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("NEW CUSTOMER", jPanel1);

        jLabel7.setText("AREA");
        jLabel7.setPreferredSize(new java.awt.Dimension(35, 19));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUDITORIUM", "MAIN BUILDING", "MBA BUILDING", "TRAINING AND PLACEMENT", "TRAINING AND DEVELOPEMENT", "CULTURAL DEPARTMENT", "LIBRARY", "READING HALL", "WORKSHOP BUILDING", "GUEST HOUSE", "SWAMI VIVEKANAND HALL", "VIKRAM SARABHAI HALL", "RADHA KRISHNA HALL", "SHARDA HALL", "SENIOR FACULTY HALL" }));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton8.setText("SUBMIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECT", "CUSTOMER ID", "RFID", "AREA", "ROOM NO", "CONTACT PERSON", "CONTACT NO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton9.setText("DELETE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(616, 616, 616)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(680, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("DELETE CUSTOMER", jPanel2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("PASSWORD");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("CONFIRM PASSWORD");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("NAME");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("MOBILE NO");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel27.setText("E-MAIL ID");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel25.setText("ADDRESS");

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton10.setText("SUBMIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel27)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1177, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NEW LOGIN", jPanel3);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("LOGIN ID");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("NEW PASSWORD");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("CONFIRM NEW PASSWORD");

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField3)
                    .addComponent(jPasswordField4))
                .addContainerGap(790, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RESET LOGIN", jPanel4);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("LOGIN ID");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton12.setText("SUBMIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton13.setText("DELETE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(623, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DELETE LOGIN", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1231, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 877, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("NEW CUSTOMER");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static ImageIcon resizeImageIcon(ImageIcon imageIcon, Integer width, Integer height) {
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D graphics2D = bufferedImage.createGraphics();
        graphics2D.drawImage(imageIcon.getImage(), 0, 0, width, height, null);
        graphics2D.dispose();
        return new ImageIcon(bufferedImage, imageIcon.getDescription());
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("web_hi_res_512.png")));
    }
    
    public void custom() throws Exception {
        jLabel19.setFocusable(false);
        jLabel21.setFocusable(false);
        jLabel22.setFocusable(false);
        jLabel24.setFocusable(false);
        ImageIcon i2 = new ImageIcon();
        BufferedImage myPicture = ImageIO.read(new File("C:\\Users\\Asus\\Documents\\NetBeansProjects\\WCS\\src\\images\\college.png"));
        i2 = resizeImageIcon(new ImageIcon(myPicture), 514, 259);
        jLabel19.setIcon(i2);
        jLabel21.setFocusable(false);
        jLabel21.setText("<html><div><p style='text-align: left;color: Green; font-size: 18px;'>" + "HINDUSTAN" + "<span style='text-align: left;color: Green; font-size: 5px;'>" + "<br>" + "COLLEGE OF SCIENCE & TECHNOLOGY" + "</span>" + "</p></div></html>");
        ImageIcon i3 = new ImageIcon();
        BufferedImage myPicture2 = ImageIO.read(new File("C:\\Users\\Asus\\Documents\\NetBeansProjects\\WCS\\src\\images\\images.jpg"));
        i3 = resizeImageIcon(new ImageIcon(myPicture2), 150, 60);
        jLabel22.setIcon(i3);
        InputMap imp = jTextField4.getInputMap(jPanel1.WHEN_FOCUSED);
        ActionMap apm = jTextField4.getActionMap();
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "click");
        apm.put("click", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                connect();
            }
        });
        InputMap imp1 = jTextField4.getInputMap(jPanel1.WHEN_FOCUSED);
        ActionMap apm1 = jTextField4.getActionMap();
        imp1.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "clear");
        apm1.put("clear", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField14.setText("");
            }
        });
        InputMap imp2 = jComboBox3.getInputMap(jPanel2.WHEN_FOCUSED);
        ActionMap apm2 = jComboBox3.getActionMap();
        imp2.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "click");
        apm2.put("click", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                displayData();
            }
        });
        InputMap imp3 = jTextField16.getInputMap(jPanel3.WHEN_FOCUSED);
        ActionMap apm3 = jTextField16.getActionMap();
        imp3.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "click");
        apm3.put("click", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                employeeData();

            }
        });

        InputMap imp4 = jTextField16.getInputMap(jPanel3.WHEN_FOCUSED);
        ActionMap apm4 = jTextField16.getActionMap();
        imp4.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "clear");
        apm4.put("clear", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPasswordField2.setText("");
                jPasswordField1.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField15.setText("");
                jTextField16.setText("");
            }
        });
        InputMap imp5 = jTextField13.getInputMap(jPanel5.WHEN_FOCUSED);
        ActionMap apm5 = jTextField13.getActionMap();
        imp5.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "click");
        apm5.put("click", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showData();
            }
        });
        InputMap imp6 = jTextField13.getInputMap(jPanel5.WHEN_FOCUSED);
        ActionMap apm6 = jTextField13.getActionMap();
        imp6.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "delete");
        apm6.put("delete", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteEmployeeData();
                jTextField13.setText("");
            }
        });
    }

    public void displayData() {
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                jLabel8.setText((String) jComboBox3.getSelectedItem());
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    Statement stmt = null;
                    ResultSet rs = null;
                    stmt = (Statement) con.createStatement();
                    String sql = "SELECT * FROM customer_details where Area = '" + (String) jComboBox3.getSelectedItem() + "'";
                    rs = stmt.executeQuery(sql);
                    if (rs.next()) {
                        rs.beforeFirst();
                        while (rs.next()) {
                            model.addRow(new Object[]{false, rs.getString("Customer_Id"), rs.getString("RFID"), rs.getString("Area"), rs.getString("Room_no"), rs.getString("Contact_person"), rs.getString("Mobile_no"),});
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Data unavailable!");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data unavailable!");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }

    public void employeeDetails() {
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String date = dateFormat.format(new Date());
                DateFormat dateFormat1 = new SimpleDateFormat("ddMMyyyy");
                String dt = dateFormat1.format(new Date());
                String lid = "";
                try {
                    char[] passn=jPasswordField2.getPassword();
                    String pass=String.valueOf(passn);
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    ResultSet rs = null;
                    ResultSet rs1 = null;
                    ResultSet rs2 = null;

                    String sql2 = "SELECT COUNT(`Login_ID`) as total FROM employee_details WHERE DOJ = '" + date + "'";
                    Statement stmt2 = (Statement) con.createStatement();
                    rs2 = stmt2.executeQuery(sql2);
                    if (rs2.next()) {
                        lid = dt + Integer.toString(rs2.getInt("total") + 1);
                    }
                    String sql1 = "SELECT * FROM employee_details WHERE Mobile_no = '" + jTextField9.getText() + "'";
                    Statement stmt1 = (Statement) con.createStatement();
                    rs1 = stmt1.executeQuery(sql1);
                    if (rs1.next()) {
                        JOptionPane.showMessageDialog(null, "Record Exists with same Mobile Number");
                    } else {
                        String sql = "INSERT INTO `employee_details`(`Login_ID`, `Password`, `Name`, `Mobile_no`,`Email`,`Address`,`DOJ`) VALUES (?,MD5(?),?,?,?,?,?)";
                        PreparedStatement stmt = con.prepareStatement(sql);
                        stmt.setString(1, lid);
                        stmt.setString(2, pass);
                        stmt.setString(3, jTextField8.getText());
                        stmt.setString(4, jTextField9.getText());
                        stmt.setString(5, jTextField15.getText());
                        stmt.setString(6, jTextField16.getText());
                        stmt.setString(7, date);
                        stmt.execute();
                        JOptionPane.showMessageDialog(null, "Record Inserted \n Login ID is :" + lid);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Record Not Inserted");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }

    public void employeeData() {
        String p1 = "";
        String p2 = "";
        char[] p11=jPasswordField2.getPassword();
        char[] p12=jPasswordField1.getPassword();
        p1 = String.valueOf(p11);
        p2 = String.valueOf(p12);
        if (p1.equals(p2)) {
            employeeDetails();
        } else {
            JOptionPane.showMessageDialog(null, "Password do no match");
        }
    }

    public void connect() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String dt = dateFormat.format(date);
        String area = (String) jComboBox1.getSelectedItem();
        String rmn = jTextField1.getText();
        String cid = "";
        if (area.equals("AUDITORIUM")) {
            cid = "AUDI" + rmn;
        }
        if (area.equals("MAIN BUILDING")) {
            cid = "MB" + rmn;
        }
        if (area.equals("MBA BUILDING")) {
            cid = "MBA" + rmn;
        }
        if (area.equals("TRAINING AND PLACEMENT")) {
            cid = "TNP" + rmn;
        }
        if (area.equals("TRAINING AND DEVELOPEMENT")) {
            cid = "TND" + rmn;
        }
        if (area.equals("CULTURAL DEPARTMENT")) {
            cid = "CD" + rmn;
        }
        if (area.equals("LIBRARY")) {
            cid = "LIB" + rmn;
        }
        if (area.equals("READING HALL")) {
            cid = "RDH" + rmn;
        }
        if (area.equals("WORKSHOP BUILDING")) {
            cid = "WB" + rmn;
        }
        if (area.equals("GUEST HOUSE")) {
            cid = "GH" + rmn;
        }
        if (area.equals("SWAMI VIVEKANAND HALL")) {
            cid = "SVH" + rmn;
        }
        if (area.equals("VIKRAM SARABHAI HALL")) {
            cid = "VSH" + rmn;
        }
        if (area.equals("RADHA KRISHNA HALL")) {
            cid = "RKH" + rmn;
        }
        if (area.equals("SHARDA HALL")) {
            cid = "SH" + rmn;
        }
        if (area.equals("SENIOR FACULTY HALL")) {
            cid = "SFH" + rmn;
        }
        final String cd = cid;
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    ResultSet rs = null;
                    ResultSet rs1 = null;
                    String sql1 = "SELECT * FROM customer_details WHERE Customer_Id = '" + cd + "'";
                    Statement stmt1 = (Statement) con.createStatement();
                    rs1 = stmt1.executeQuery(sql1);
                    if (rs1.next()) {
                        JOptionPane.showMessageDialog(null, "Record Exists");
                    } else {
                        String sql = "INSERT INTO `customer_details`(`Customer_ID`, `Area`, `Room_no`, `Contact_person`, `Mobile_no`,`Email`, `RFID`,`Password`) VALUES (?,?,?,?,?,?,?,md5(?))";
                        PreparedStatement stmt = con.prepareStatement(sql);
                        stmt.setString(1, cd);
                        stmt.setString(2, (String) jComboBox1.getSelectedItem());
                        stmt.setString(3, jTextField1.getText());
                        stmt.setString(4, jTextField2.getText());
                        stmt.setString(5, jTextField3.getText());
                        stmt.setString(6, jTextField14.getText());
                        stmt.setString(7, jTextField4.getText());
                        stmt.setString(8, jTextField3.getText());
                        stmt.execute();
                        String sql2 = "INSERT INTO payments (`Receipt_no`,`Date`, `customer_ID`, `Amount`, `Due`, `Excess`,`collected_By`) VALUES (?,?,?,?,?,?,?)";
                        PreparedStatement stmt2 = con.prepareStatement(sql2);
                        stmt2.setString(1, cd);
                        stmt2.setString(2, dt);
                        stmt2.setString(3, cd);
                        stmt2.setString(4, "0");
                        stmt2.setString(5, "0");
                        stmt2.setString(6, "0");
                        stmt2.setString(7, "0");
                        stmt2.execute();
                        JOptionPane.showMessageDialog(null, "Record Inserted");
                        jLabel24.setText("<html><div style='text-align: left;'>" + "Customer ID:" + "&nbsp;&nbsp;" + cd + "</div><br><div style='text-align: left;'>" + "Name:" + "&nbsp;&nbsp;" + jTextField2.getText() + "</div><br><div style='text-align: left;'>" + "Contact No:" + "&nbsp;&nbsp;" + jTextField3.getText() + "</div><br><div style='text-align: left;'>" + "Area:" + "&nbsp;&nbsp;" + (String) jComboBox1.getSelectedItem() + "</div><br><div style='text-align: left;'>" + "Room No:" + "&nbsp;&nbsp;" + jTextField1.getText() + "</div></html>");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Record Not Inserted");
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);

    }

    private void printRecord(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Record");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.translate(pageFormat.getImageableX() + 10, pageFormat.getImageableY() + 10);
                graphics2D.scale(0.5, 0.5);

                panel.paint(graphics2D);

                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        if (returningResult) {
            try {
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }

    public void showData() {
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    Statement stmt = null;
                    ResultSet rs = null;
                    stmt = (Statement) con.createStatement();
                    String sql = "SELECT * FROM employee_details where Login_ID = '" + jTextField13.getText() + "'";
                    rs = stmt.executeQuery(sql);
                    if (rs.next()) {
                        jLabel14.setText("NAME - " + rs.getString("Name"));
                        jLabel20.setText("MOBILE NO - " + rs.getString("Mobile_no"));
                                                jLabel9.setText("ADDRESS - " + rs.getString("Address"));

                    } else {
                        JOptionPane.showMessageDialog(null, "Data unavailable!");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Data unavailable!");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Component component = (Component) evt.getSource();
        JFrame frame = (JFrame) SwingUtilities.getRoot(component);
        try {
            Home obj = new Home();
            obj.open1(frame);
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        connect();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String area = (String) jComboBox1.getSelectedItem();
        String rmn = jTextField1.getText();
        String cid = "";
        if (area.equals("AUDITORIUM")) {
            cid = "AUDI" + rmn;
        }
        if (area.equals("MAIN BUILDING")) {
            cid = "MB" + rmn;
        }
        if (area.equals("MBA BUILDING")) {
            cid = "MBA" + rmn;
        }
        if (area.equals("TRAINING AND PLACEMENT")) {
            cid = "TNP" + rmn;
        }
        if (area.equals("TRAINING AND DEVELOPEMENT")) {
            cid = "TND" + rmn;
        }
        if (area.equals("CULTURAL DEPARTMENT")) {
            cid = "CD" + rmn;
        }
        if (area.equals("LIBRARY")) {
            cid = "LIB" + rmn;
        }
        if (area.equals("READING HALL")) {
            cid = "RDH" + rmn;
        }
        if (area.equals("WORKSHOP BUILDING")) {
            cid = "WB" + rmn;
        }
        if (area.equals("GUEST HOUSE")) {
            cid = "GH" + rmn;
        }
        if (area.equals("SWAMI VIVEKANAND HALL")) {
            cid = "SVH" + rmn;
        }
        if (area.equals("VIKRAM SARABHAI HALL")) {
            cid = "VSH" + rmn;
        }
        if (area.equals("RADHA KRISHNA HALL")) {
            cid = "RKH" + rmn;
        }
        if (area.equals("SHARDA HALL")) {
            cid = "SH" + rmn;
        }
        if (area.equals("SENIOR FACULTY HALL")) {
            cid = "SFH" + rmn;
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        final String cd = cid;
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    Statement stmt = null;
                    ResultSet rs = null;
                    stmt = (Statement) con.createStatement();
                    String query = "UPDATE `customer_details` SET `RFID`='" + jTextField4.getText() + "' WHERE Customer_Id = '" + cd + "'";
                    PreparedStatement preparedStmt = con.prepareStatement(query);
                    preparedStmt.execute();
                    JOptionPane.showMessageDialog(null, "Record Updated");
                    jLabel24.setText("<html><div style='text-align: left;'>" + "Customer ID:" + "&nbsp;&nbsp;" + cd + "</div><br><div style='text-align: left;'>" + "Name:" + "&nbsp;&nbsp;" + jTextField2.getText() + "</div><br><div style='text-align: left;'>" + "Contact No:" + "&nbsp;&nbsp;" + jTextField3.getText() + "</div><br><div style='text-align: left;'>" + "Area:" + "&nbsp;&nbsp;" + (String) jComboBox1.getSelectedItem() + "</div><br><div style='text-align: left;'>" + "Room No:" + "&nbsp;&nbsp;" + jTextField1.getText() + "</div></html>");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Record Not Updated");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        displayData();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                String col[] = new String[100];
                Boolean checked = false;
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    checked = Boolean.valueOf(jTable1.getValueAt(i, 0).toString());
                    col[i] = jTable1.getValueAt(i, 1).toString();
                    //DISPLAY
                    if (checked) {
                        try {
                            Class.forName("com.mysql.jdbc.Driver");
                        } catch (ClassNotFoundException e) {
                            e.printStackTrace();
                        }
                        try {
//                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcs?zeroDateTimeBehavior=convertToNull", "root", "");
                            Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                            Statement stmt = null;
                            ResultSet rs = null;
                            stmt = (Statement) con.createStatement();
                            String sql = "delete from customer_details where `Customer_ID` = '" + col[i] + "'";
                            stmt.executeUpdate(sql);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Unable to delete!");
                        }
                    }
                }
                model.setRowCount(0);
                displayData();
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed
    JFrame fr;

    public void open(JFrame frame) {
        fr = frame;
        this.setVisible(true);
        frame.dispose();
    }
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        employeeData();


    }//GEN-LAST:event_jButton10ActionPerformed
    String hashtext = "";
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                String lid = "";
                lid = jTextField10.getText();
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    ResultSet rs = null;
                    ResultSet rs1 = null;
                    String sql1 = "SELECT * FROM employee_details WHERE Login_Id = '" + lid + "'";
                    Statement stmt1 = (Statement) con.createStatement();
                    rs1 = stmt1.executeQuery(sql1);
                    if (rs1.next()) {
                        rs1.beforeFirst();
                        char[] p11=jPasswordField3.getPassword();
                        char[] p12=jPasswordField4.getPassword();
                        String p1 = String.valueOf(p11);
                        String p2 = String.valueOf(p12);
                        if (p1.equals(p2)) {
                            MessageDigest md;
                            String pass = p1;

                            try {
                                md = MessageDigest.getInstance("MD5");

            // digest() method is called to calculate message digest 
                                //  of an input digest() return array of byte 
                                byte[] messageDigest = md.digest(pass.getBytes());

                                // Convert byte array into signum representation 
                                BigInteger no = new BigInteger(1, messageDigest);

                                // Convert message digest into hex value 
                                hashtext = no.toString(16);
                                while (hashtext.length() < 32) {
                                    hashtext = "0" + hashtext;
                                }
//            System.out.println(hashtext1);
                            } catch (NoSuchAlgorithmException exe) {
                                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, exe);
                            }
                            String query = "UPDATE `employee_details` SET `Password`='" + hashtext + "' WHERE Login_ID = '" + lid + "'";
                            PreparedStatement preparedStmt = con.prepareStatement(query);
                            preparedStmt.execute();
                            JOptionPane.showMessageDialog(null, "Record Updated");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Login Id doesn't exists");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Record Not Updated");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        showData();
    }//GEN-LAST:event_jButton12ActionPerformed
    public void deleteEmployeeData() {
        String dlid=jTextField13.getText();
        final JDialog dialog = new JDialog();
        dialog.setUndecorated(true);
        dialog.getRootPane().setOpaque(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setBackground(new Color(0, 0, 0, 100));
        dialog.add(new ImagePanel());
        dialog.pack();
        dialog.setSize(300, 300);
        dialog.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://sql178.main-hosting.eu/u491619435_wcs", "u491619435_wcs", "wcshcst@2020");
                    Statement stmt = null;
                    ResultSet rs = null;
                    stmt = (Statement) con.createStatement();
                    String sql = "delete from employee_details where `Login_ID` = '" + dlid + "'";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Deleted!");
                    jLabel14.setText("");
                    jLabel20.setText("");
                    jLabel9.setText("");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Unable to delete!");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    dialog.dispose();
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }

            }
        };
        worker.execute();
        dialog.setVisible(true);
    }
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        deleteEmployeeData();
        jTextField13.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        printRecord(jPanel7);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Component component = (Component) evt.getSource();
        JFrame frame = (JFrame) SwingUtilities.getRoot(component);
        try {
            Payments obj = new Payments();
            obj.open2(frame);
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Component component = (Component) evt.getSource();
        JFrame frame = (JFrame) SwingUtilities.getRoot(component);
        try {
            Messagess obj = new Messagess();
            obj.open3(frame);
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administration().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Administration.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}

class ImagePanel extends JPanel {

    private static final long serialVersionUID = 1L;

    Image image;

    String usingSystemProperty = System.getProperty("user.dir");
    //System.out.println(usingSystemProperty);

    public ImagePanel() {
        image = Toolkit.getDefaultToolkit().createImage("C:\\Users\\Asus\\Documents\\NetBeansProjects\\WCS\\src\\images\\25.gif");
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, this);
        }
    }
}
